### ISSUE TITLE
Errors in teminal when selecting JSculpt Tab

### ISSUE THREAD

**Issue by OBI-Ron** [jayanam/jsculpt-tools#1]
Ubuntu 18.04
AMD 64
Blender 2.82 Official
I downloaded the latest JSculpt.  After installing and starting a new session the JSculpt tab appears, but if I select it, I see the following in the terminal window:

WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:8161 bpy_class_call: unable to get Python class for RNA struct 'FSC_PT_Panel'

**Comment by jayanam** [comment]
Fixed

**Comment by OBI-Ron** [comment]
...and verified - thanks for all of the hard work you do to make these tools and tutorials available!!
    On Saturday, February 15, 2020, 10:33:11 AM CST, Jayanam <notifications@github.com> wrote:  
 
 
Fixed

**Comment by jayanam** [comment]
Thx a lot!
